version: '3.9'

services:
    telegram-bot:
        container_name: healthcheck-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
          - ./src:/src
        depends_on:
          - redis

    redis:
        container_name: healthcheck-redis
        restart: unless-stopped
        image: redis:6.2.14
        ports:
          -   6379:${REDIS_PORT}
        volumes:
            -   ./redis:/data
